### ISSUE TITLE
目前最新版(0.4.2)在springboot3上使用时会产生冲突

### ISSUE THREAD

**Issue by zainmiku** [seepine/spring-boot-starter-wrap#1]
以下是报错日志
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-21T22:34:56.965+08:00 ERROR 18456 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Cannot invoke "com.seepine.wrap.entity.WrapProperties.getResponseAdviceOrder()" because "this.wrapProperties" is null

**Comment by seepine** [comment]
springboot3还未正式发布所有没做兼容，改天有时间我试一下

**Comment by seepine** [comment]
0.5.0+应该已解决
