### ISSUE TITLE
集成swagger的项目，swagger-ui输出的返回结构没有被wrap

### ISSUE THREAD

**Issue by JimYan** [seepine/spring-boot-starter-wrap#2]
swagger-ui描述的回包，丢失了code和data字段。
<img width="823" alt="image" src="https://user-images.githubusercontent.com/4209007/198020703-e247bceb-9884-4a74-b377-6a5082260a46.png">

**Comment by seepine** [comment]
这个是期望的结果
1. swagger是直接扫的controller的返回对象
2. 文档上的返回值不应该每个接口都体现无意义的包装结构，在查看大厂或银行文档时，也会在开头统一描述返回体，在具体接口中就不再介绍，会直接展示业务结构
3. 若真需要体现出来的话，那只能在接口中显性返回对象，例如
```java
public R<User> getUser(){
    return R.ok(new User());
}
```
